# Generated by Django 4.2.2 on 2024-03-02 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_communication_reading_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='activity',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contact_course', to='lms.course'),
            preserve_default=False,
        ),
    ]
