# Generated by Django 4.2.2 on 2024-03-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_user_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='user_course', to='lms.course', verbose_name='Курс'),
        ),
    ]
