# Generated by Django 4.2.2 on 2024-03-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_user_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='country',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
