# Generated by Django 4.2.2 on 2024-03-05 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_contacts_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
            ],
            options={
                'verbose_name': 'Статус лекции',
                'verbose_name_plural': 'Статус лекции',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='modulecompletion',
            name='module',
        ),
        migrations.RemoveField(
            model_name='modulecompletion',
            name='student',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='additional',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='module',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='text',
        ),
        migrations.RemoveField(
            model_name='task',
            name='module',
        ),
        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecture_course', to='lms.course'),
        ),
        migrations.AddField(
            model_name='task',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_lecture', to='lms.lecture'),
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='ModuleCompletion',
        ),
        migrations.AddField(
            model_name='lecturecompletion',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.lecture'),
        ),
        migrations.AddField(
            model_name='lecturecompletion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
