# Generated by Django 4.2.2 on 2024-03-10 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_remove_tasksolution_is_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'ordering': ['-id'], 'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакт'},
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                ('file', models.FileField(upload_to='uploads/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_upload', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Загрузка',
                'verbose_name_plural': 'Загрузки',
                'ordering': ['-id'],
            },
        ),
    ]
