# Generated by Django 4.2.2 on 2024-03-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_alter_contacts_options_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.BooleanField(default=False),
        ),
    ]
