# Generated by Django 4.2.2 on 2024-04-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0017_template_alter_user_role_mailbox_emailsmtp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsmtp',
            name='id_inbox',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='provider',
            field=models.CharField(choices=[('google', 'google'), ('webmail', 'webmail')], max_length=20),
        ),
    ]
