# Generated by Django 4.2.2 on 2024-05-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0019_emailsmtp_is_answer_emailsmtp_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsmtp',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
