# Generated by Django 4.2.2 on 2024-05-25 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0020_emailsmtp_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='template',
            name='files',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='template',
            name='from_mailbox',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='template', to='lms.mailbox'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='template',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
