# Generated by Django 4.2.2 on 2024-05-26 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0021_template_body_template_files_template_from_mailbox_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='body',
        ),
    ]
