# Generated by Django 4.2.2 on 2024-05-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0022_remove_template_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='smtp_server',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
